# Generated by Django 2.2.16 on 2020-10-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alacartebackend', '0002_auto_20201003_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employeeType',
            field=models.PositiveSmallIntegerField(choices=[(0, 'WAITER'), (1, 'COOK'), (2, 'ADMIN')], default=0),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.PositiveSmallIntegerField(choices=[(0, 'STARTER'), (1, 'MAIN_COURSE'), (2, 'DESSERT'), (3, 'BEVERAGE'), (4, 'CAFETERIA')], default=0),
        ),
    ]
